### ISSUE TITLE
Strange errors while using promesa with code that throw

### ISSUE THREAD

**Issue by mauricioszabo** [funcool/promesa#86] opened 2021-03-18 18:24 UTC
Why does the following code does not compile?

```clojure
(p/do!
  (p/delay 2000)
  (throw (ex-info "fail" {})))
```
It always fail to compile with the error:

```
 245 |           (p/do!
------------------^-------------------------------------------------------------
 Use of undeclared Var <current-namespace>/ignore
--------------------------------------------------------------------------------
```

**Comment by niwinz** [comment] 2021-06-01 06:15
Looks something unrelarelated to promesa, becaise promesa does not have nothing called `ignore` inside the `do!` macro

**Comment by p-himik** [comment] 2022-02-01 18:46
@mauricioszabo Were you using shadow-cljs when that happened, by any chance?

**Comment by mauricioszabo** [comment] 2022-02-01 21:22
@p-himik yes, I was.

**Comment by p-himik** [comment] 2022-02-01 21:25
Good, because I could reproduce it only there. :) After some investigation, I've notified thheller about it: https://clojurians.slack.com/archives/C6N245JGG/p1643740157399209

**Comment by niwinz** [comment] 2022-02-23 18:39
So I closing this one, thanks for all the work and research about this issue.

**Closed by niwinz** 2022-02-23 18:39 UTC
